'use strict';

/**
 * List of US Presidents
 * @type {Array}
 */
module.exports = [
  { name: 'George Washington',
    n: '1',
    wiki: 'http://en.wikipedia.org/wiki/George_Washington',
    start: '30/04/1789',
    end: '4/03/1797',
    party: 'Independent ',
    portrait: 'GeorgeWashington.jpg',
    thumb: 'thmb_GeorgeWashington.jpg',
    state: 'Virginia' },
  { name: 'John Adams',
    n: '2',
    wiki: 'http://en.wikipedia.org/wiki/John_Adams',
    start: '4/03/1797',
    end: '4/03/1801',
    party: 'Federalist ',
    portrait: 'JohnAdams.jpg',
    thumb: 'thmb_JohnAdams.jpg',
    state: 'Massachusetts' },
  { name: 'Thomas Jefferson',
    n: '3',
    wiki: 'http://en.wikipedia.org/wiki/Thomas_Jefferson',
    start: '4/03/1801',
    end: '4/03/1809',
    party: 'Democratic-Republican ',
    portrait: 'Thomasjefferson.gif',
    thumb: 'thmb_Thomasjefferson.gif',
    state: 'Virginia' },
  { name: 'James Madison',
    n: '4',
    wiki: 'http://en.wikipedia.org/wiki/James_Madison',
    start: '4/03/1809',
    end: '4/03/1817',
    party: 'Democratic-Republican ',
    portrait: 'JamesMadison.gif',
    thumb: 'thmb_JamesMadison.gif',
    state: 'Virginia' },
  { name: 'James Monroe',
    n: '5',
    wiki: 'http://en.wikipedia.org/wiki/James_Monroe',
    start: '4/03/1817',
    end: '4/03/1825',
    party: 'Democratic-Republican ',
    portrait: 'JamesMonroe.gif',
    thumb: 'thmb_JamesMonroe.gif',
    state: 'Virginia' },
  { name: 'John Quincy Adams',
    n: '6',
    wiki: 'http://en.wikipedia.org/wiki/John_Quincy_Adams',
    start: '4/03/1825',
    end: '4/03/1829',
    party: 'Democratic-Republican/National Republican ',
    portrait: 'JohnQuincyAdams.gif',
    thumb: 'thmb_JohnQuincyAdams.gif',
    state: 'Massachusetts' },
  { name: 'Andrew Jackson',
    n: '7',
    wiki: 'http://en.wikipedia.org/wiki/Andrew_Jackson',
    start: '4/03/1829',
    end: '4/03/1837',
    party: 'Democratic ',
    portrait: 'Andrew_jackson_head.gif',
    thumb: 'thmb_Andrew_jackson_head.gif',
    state: 'Tennessee' },
  { name: 'Martin Van Buren',
    n: '8',
    wiki: 'http://en.wikipedia.org/wiki/Martin_Van_Buren',
    start: '4/03/1837',
    end: '4/03/1841',
    party: 'Democratic ',
    portrait: 'MartinVanBuren.gif',
    thumb: 'thmb_MartinVanBuren.gif',
    state: 'New York' },
  { name: 'William Henry Harrison',
    n: '9',
    wiki: 'http://en.wikipedia.org/wiki/William_Henry_Harrison',
    start: '4/03/1841',
    end: '4/04/1841',
    party: 'Whig',
    portrait: 'WilliamHenryHarrison.gif',
    thumb: 'thmb_WilliamHenryHarrison.gif',
    state: 'Ohio' },
  { name: 'John Tyler',
    n: '10',
    wiki: 'http://en.wikipedia.org/wiki/John_Tyler',
    start: '4/04/1841',
    end: '4/03/1845',
    party: 'Whig',
    portrait: 'JohnTyler.jpg',
    thumb: 'thmb_JohnTyler.jpg',
    state: 'Virginia' },
  { name: 'James K. Polk',
    n: '11',
    wiki: 'http://en.wikipedia.org/wiki/James_K._Polk',
    start: '4/03/1845',
    end: '4/03/1849',
    party: 'Democratic ',
    portrait: 'JamesKPolk.gif',
    thumb: 'thmb_JamesKPolk.gif',
    state: 'Tennessee' },
  { name: 'Zachary Taylor',
    n: '12',
    wiki: 'http://en.wikipedia.org/wiki/Zachary_Taylor',
    start: '4/03/1849',
    end: '9/07/1850',
    party: 'Whig',
    portrait: 'ZacharyTaylor.jpg',
    thumb: 'thmb_ZacharyTaylor.jpg',
    state: 'Louisiana' },
  { name: 'Millard Fillmore',
    n: '13',
    wiki: 'http://en.wikipedia.org/wiki/Millard_Fillmore',
    start: '9/07/1850',
    end: '4/03/1853',
    party: 'Whig',
    portrait: 'MillardFillmore.png',
    thumb: 'thmb_MillardFillmore.png',
    state: 'New York' },
  { name: 'Franklin Pierce',
    n: '14',
    wiki: 'http://en.wikipedia.org/wiki/Franklin_Pierce',
    start: '4/03/1853',
    end: '4/03/1857',
    party: 'Democratic ',
    portrait: 'FranklinPierce.gif',
    thumb: 'thmb_FranklinPierce.gif',
    state: 'New Hampshire' },
  { name: 'James Buchanan',
    n: '15',
    wiki: 'http://en.wikipedia.org/wiki/James_Buchanan',
    start: '4/03/1857',
    end: '4/03/1861',
    party: 'Democratic ',
    portrait: 'JamesBuchanan.gif',
    thumb: 'thmb_JamesBuchanan.gif',
    state: 'Pennsylvania' },
  { name: 'Abraham Lincoln',
    n: '16',
    wiki: 'http://en.wikipedia.org/wiki/Abraham_Lincoln',
    start: '4/03/1861',
    end: '15/04/1865',
    party: 'Republican/National Union',
    portrait: 'AbrahamLincoln.jpg',
    thumb: 'thmb_AbrahamLincoln.jpg',
    state: 'Illinois' },
  { name: 'Andrew Johnson',
    n: '17',
    wiki: 'http://en.wikipedia.org/wiki/Andrew_Johnson',
    start: '15/04/1865',
    end: '4/03/1869',
    party: 'Democratic/National Union',
    portrait: 'AndrewJohnson.gif',
    thumb: 'thmb_AndrewJohnson.gif',
    state: 'Tennessee' },
  { name: 'Ulysses S. Grant',
    n: '18',
    wiki: 'http://en.wikipedia.org/wiki/Ulysses_S._Grant',
    start: '4/03/1869',
    end: '4/03/1877',
    party: 'Republican ',
    portrait: 'UlyssesSGrant.gif',
    thumb: 'thmb_UlyssesSGrant.gif',
    state: 'Ohio' },
  { name: 'Rutherford B. Hayes',
    n: '19',
    wiki: 'http://en.wikipedia.org/wiki/Rutherford_B._Hayes',
    start: '4/03/1877',
    end: '4/03/1881',
    party: 'Republican ',
    portrait: 'RutherfordBHayes.png',
    thumb: 'thmb_RutherfordBHayes.png',
    state: 'Ohio' },
  { name: 'James A. Garfield',
    n: '20',
    wiki: 'http://en.wikipedia.org/wiki/James_A._Garfield',
    start: '4/03/1881',
    end: '19/09/1881',
    party: 'Republican ',
    portrait: 'James_Garfield.jpg',
    thumb: 'thmb_James_Garfield.jpg',
    state: 'Ohio' },
  { name: 'Chester A. Arthur',
    n: '21',
    wiki: 'http://en.wikipedia.org/wiki/Chester_A._Arthur',
    start: '19/09/1881',
    end: '4/03/1885',
    party: 'Republican ',
    portrait: 'ChesterAArthur.gif',
    thumb: 'thmb_ChesterAArthur.gif',
    state: 'New York' },
  { name: 'Grover Cleveland',
    n: '22',
    wiki: 'http://en.wikipedia.org/wiki/Grover_Cleveland',
    start: '4/03/1885',
    end: '4/03/1889',
    party: 'Democratic ',
    portrait: 'Grover_Cleveland_2.jpg',
    thumb: 'thmb_Grover_Cleveland_2.jpg',
    state: 'New York' },
  { name: 'Benjamin Harrison',
    n: '23',
    wiki: 'http://en.wikipedia.org/wiki/Benjamin_Harrison',
    start: '4/03/1889',
    end: '4/03/1893',
    party: 'Republican ',
    portrait: 'BenjaminHarrison.gif',
    thumb: 'thmb_BenjaminHarrison.gif',
    state: 'Indiana' },
  { name: 'Grover Cleveland (2nd term)',
    n: '24',
    wiki: 'http://en.wikipedia.org/wiki/Grover_Cleveland',
    start: '4/03/1893',
    end: '4/03/1897',
    party: 'Democratic ',
    portrait: 'Grover_Cleveland.jpg',
    thumb: 'thmb_Grover_Cleveland.jpg',
    state: 'New York' },
  { name: 'William McKinley',
    n: '25',
    wiki: 'http://en.wikipedia.org/wiki/William_McKinley',
    start: '4/03/1897',
    end: '14/9/1901',
    party: 'Republican ',
    portrait: 'WilliamMcKinley.gif',
    thumb: 'thmb_WilliamMcKinley.gif',
    state: 'Ohio' },
  { name: 'Theodore Roosevelt',
    n: '26',
    wiki: 'http://en.wikipedia.org/wiki/Theodore_Roosevelt',
    start: '14/9/1901',
    end: '4/3/1909',
    party: 'Republican ',
    portrait: 'TheodoreRoosevelt.jpg',
    thumb: 'thmb_TheodoreRoosevelt.jpg',
    state: 'New York' },
  { name: 'William Howard Taft',
    n: '27',
    wiki: 'http://en.wikipedia.org/wiki/William_Howard_Taft',
    start: '4/3/1909',
    end: '4/03/1913',
    party: 'Republican ',
    portrait: 'WilliamHowardTaft.jpg',
    thumb: 'thmb_WilliamHowardTaft.jpg',
    state: 'Ohio' },
  { name: 'Woodrow Wilson',
    n: '28',
    wiki: 'http://en.wikipedia.org/wiki/Woodrow_Wilson',
    start: '4/03/1913',
    end: '4/03/1921',
    party: 'Democratic ',
    portrait: 'WoodrowWilson.gif',
    thumb: 'thmb_WoodrowWilson.gif',
    state: 'New Jersey' },
  { name: 'Warren G. Harding',
    n: '29',
    wiki: 'http://en.wikipedia.org/wiki/Warren_G._Harding',
    start: '4/03/1921',
    end: '2/8/1923',
    party: 'Republican ',
    portrait: 'WarrenGHarding.gif',
    thumb: 'thmb_WarrenGHarding.gif',
    state: 'Ohio' },
  { name: 'Calvin Coolidge',
    n: '30',
    wiki: 'http://en.wikipedia.org/wiki/Calvin_Coolidge',
    start: '2/8/1923',
    end: '4/03/1929',
    party: 'Republican ',
    portrait: 'CoolidgeWHPortrait.gif',
    thumb: 'thmb_CoolidgeWHPortrait.gif',
    state: 'Massachusetts' },
  { name: 'Herbert Hoover',
    n: '31',
    wiki: 'http://en.wikipedia.org/wiki/Herbert_Hoover',
    start: '4/03/1929',
    end: '4/03/1933',
    party: 'Republican ',
    portrait: 'HerbertHover.gif',
    thumb: 'thmb_HerbertHover.gif',
    state: 'Iowa' },
  { name: 'Franklin D. Roosevelt',
    n: '32',
    wiki: 'http://en.wikipedia.org/wiki/Franklin_D._Roosevelt',
    start: '4/03/1933',
    end: '12/4/1945',
    party: 'Democratic',
    portrait: 'FranklinDRoosevelt.gif',
    thumb: 'thmb_FranklinDRoosevelt.gif',
    state: 'New York' },
  { name: 'Harry S. Truman',
    n: '33',
    wiki: 'http://en.wikipedia.org/wiki/Harry_S._Truman',
    start: '12/4/1945',
    end: '20/01/1953',
    party: 'Democratic',
    portrait: 'HarryTruman.jpg',
    thumb: 'thmb_HarryTruman.jpg',
    state: 'Missouri' },
  { name: 'Dwight D. Eisenhower',
    n: '34',
    wiki: 'http://en.wikipedia.org/wiki/Dwight_D._Eisenhower',
    start: '20/01/1953',
    end: '20/01/1961',
    party: 'Republican ',
    portrait: 'Dwight_D_Eisenhower.jpg',
    thumb: 'thmb_Dwight_D_Eisenhower.jpg',
    state: 'Texas' },
  { name: 'John F. Kennedy',
    n: '35',
    wiki: 'http://en.wikipedia.org/wiki/John_F._Kennedy',
    start: '20/01/1961',
    end: '22/11/1963',
    party: 'Democratic',
    portrait: 'John_F_Kennedy.jpg',
    thumb: 'thmb_John_F_Kennedy.jpg',
    state: 'Massachusetts' },
  { name: 'Lyndon B. Johnson',
    n: '36',
    wiki: 'http://en.wikipedia.org/wiki/Lyndon_B._Johnson',
    start: '22/11/1963',
    end: '20/1/1969',
    party: 'Democratic',
    portrait: 'Lyndon_B_Johnson.gif',
    thumb: 'thmb_Lyndon_B_Johnson.gif',
    state: 'Texas' },
  { name: 'Richard Nixon',
    n: '37',
    wiki: 'http://en.wikipedia.org/wiki/Richard_Nixon',
    start: '20/1/1969',
    end: '9/8/1974',
    party: 'Republican',
    portrait: 'RichardNixon.gif',
    thumb: 'thmb_RichardNixon.gif',
    state: 'California' },
  { name: 'Gerald Ford',
    n: '38',
    wiki: 'http://en.wikipedia.org/wiki/Gerald_Ford',
    start: '9/8/1974',
    end: '20/01/1977',
    party: 'Republican',
    portrait: 'Gerald_R_Ford.jpg',
    thumb: 'thmb_Gerald_R_Ford.jpg',
    state: 'Michigan' },
  { name: 'Jimmy Carter',
    n: '39',
    wiki: 'http://en.wikipedia.org/wiki/Jimmy_Carter',
    start: '20/01/1977',
    end: '20/01/1981',
    party: 'Democratic ',
    portrait: 'James_E_Carter.gif',
    thumb: 'thmb_James_E_Carter.gif',
    state: 'Georgia' },
  { name: 'Ronald Reagan',
    n: '40',
    wiki: 'http://en.wikipedia.org/wiki/Ronald_Reagan',
    start: '20/01/1981',
    end: '20/01/1989',
    party: 'Republican ',
    portrait: 'ReaganWH.jpg',
    thumb: 'thmb_ReaganWH.jpg',
    state: 'California' },
  { name: 'George H. W. Bush',
    n: '41',
    wiki: 'http://en.wikipedia.org/wiki/George_H._W._Bush',
    start: '20/01/1989',
    end: '20/01/1993',
    party: 'Republican ',
    portrait: 'George_H_W_Bush.gif',
    thumb: 'thmb_George_H_W_Bush.gif',
    state: 'Texas' },
  { name: 'Bill Clinton',
    n: '42',
    wiki: 'http://en.wikipedia.org/wiki/Bill_Clinton',
    start: '20/01/1993',
    end: '20/01/2001',
    party: 'Democratic ',
    portrait: 'Clinton.jpg',
    thumb: 'thmb_Clinton.jpg',
    state: 'Arkansas' },
  { name: 'George W. Bush',
    n: '43',
    wiki: 'http://en.wikipedia.org/wiki/George_W._Bush',
    start: '20/01/2001',
    end: '20/01/2009',
    party: 'Republican ',
    portrait: 'George_W_Bush.jpg',
    thumb: 'thmb_George_W_Bush.jpg',
    state: 'Texas' },
  { name: 'Barack Obama',
    n: '44',
    wiki: 'http://en.wikipedia.org/wiki/Barack_Obama',
    start: '20/01/2009',
    end: 'Incumbent ',
    party: '  Democratic   ',
    portrait: 'Barack_Obama.jpg',
    thumb: 'thmb_Barack_Obama.jpg',
    state: 'Illinois' }];
